export const Engines = [
  {id: 0, name: "Отсутствует"},
  {id: 1, name: "Неизвестный"},
  {id: 2, name: "4A Engine"},
  {id: 3, name: "Amazon Lumberyard"},
  {id: 4, name: "Anvil Engine"},
  {id: 5, name: "BigWorld"},
  {id: 6, name: "Clausewitz Engine"},
  {id: 7, name: "Clickteam Fusion"},
  {id: 8, name: "Cocos2D"},
  {id: 9, name: "Creation Engine"},
  {id: 10, name: "CryEngine"},
  {id: 11, name: "Dagor Engine"},
  {id: 12, name: "Decima"},
  {id: 13, name: "Divinity Engine"},
  {id: 14, name: "Enfusion Engine"},
  {id: 15, name: "Fox Engine"},
  {id: 16, name: "Frostbite"},
  {id: 17, name: "Gamebryo"},
  {id: 18, name: "GameMaker"},
  {id: 19, name: "Glacier Engine"},
  {id: 20, name: "Godot"},
  {id: 21, name: "Id Tech"},
  {id: 22, name: "IW Engine"},
  {id: 23, name: "LWJGL"},
  {id: 24, name: "RAGE"},
  {id: 25, name: "Real Virtuality"},
  {id: 26, name: "REDengine"},
  {id: 27, name: "Ren'Py"},
  {id: 28, name: "RenderWare"},
  {id: 29, name: "Serious Engine"},
  {id: 30, name: "Source"},
  {id: 31, name: "Unigine"},
  {id: 32, name: "Unity"},
  {id: 33, name: "Unreal Engine"},
  {id: 34, name: "X-Ray"},
  {id: 35, name: "XNA/Monogame"},
  {id: 36, name: "Illusion Engine"},
  {id: 37, name: "EGO"},
  {id: 38, name: "Prism3D"},
  {id: 39, name: "GIANTS Engine"},
  {id: 40, name: "Liquid Engine"},
  {id: 41, name: "Box2D"},
  {id: 42, name: "EAGL"},
  {id: 43, name: "RE Engine"},
  {id: 44, name: "Dunia Engine"},
  {id: 45, name: "Chrome Engine"},
  {id: 46, name: "Phyre Engine"},
  {id: 47, name: "TellTale Tool"},
  {id: 48, name: "HTML5/Flash"},
  {id: 49, name: "Apex Engine"},
  {id: 50, name: "GZDoom"}
]