export const Genres = [
  {id: 0, name: "Отсутствует"},
  {id: 1, name: "Slasher"},
  {id: 2, name: "Action"},
  {id: 3, name: "Action/RPG"},
  {id: 4, name: "Action/Adventure"},
  {id: 5, name: "Arcade"},
  {id: 6, name: "Battle Royale"},
  {id: 7, name: "Beat 'Em Up"},
  {id: 8, name: "Clicker"},
  {id: 9, name: "Diabloid"},
  {id: 10, name: "Fighting"},
  {id: 11, name: "Shooter (First-Person)"},
  {id: 12, name: "Horror"},
  {id: 13, name: "Hypercasual"},
  {id: 14, name: "Interactive Movie"},
  {id: 15, name: "JRPG"},
  {id: 16, name: "Shooter (Extraction)"},
  {id: 17, name: "MMORPG"},
  {id: 18, name: "MOBA"},
  {id: 19, name: "Platformer"},
  {id: 20, name: "Puzzle"},
  {id: 21, name: "Racing"},
  {id: 22, name: "Strategy (Real-Time)"},
  {id: 23, name: "Rhythm"},
  {id: 24, name: "Roguelike"},
  {id: 25, name: "RPG"},
  {id: 26, name: "Sandbox"},
  {id: 27, name: "Shooter (Scroll)"},
  {id: 28, name: "Shoot 'Em Up"},
  {id: 29, name: "Simulator"},
  {id: 30, name: "Sports"},
  {id: 31, name: "Action/Stealth"},
  {id: 32, name: "Survival"},
  {id: 33, name: "Survival Horror"},
  {id: 34, name: "Shooter (Top-Down)"},
  {id: 35, name: "Tower Defense"},
  {id: 36, name: "Strategy (Turn-Based)"},
  {id: 37, name: "Visual Novel"},
  {id: 38, name: "Shooter (Isometric)"},
  {id: 39, name: "Souls-like"},
  {id: 40, name: "Card Game"}
]