export const Genres = [
  {id: 0, name: "Отсутствует"},
  {id: 1, name: "4X"},
  {id: 2, name: "Action"},
  {id: 3, name: "Action/RPG"},
  {id: 4, name: "Adventure"},
  {id: 5, name: "Arena Shooter"},
  {id: 6, name: "Battle Royale"},
  {id: 7, name: "Beat 'Em Up"},
  {id: 8, name: "Clicker"},
  {id: 9, name: "Diabloid"},
  {id: 10, name: "Fighting"},
  {id: 11, name: "FPS"},
  {id: 12, name: "Horror"},
  {id: 13, name: "Hypercasual"},
  {id: 14, name: "Interactive Movie"},
  {id: 15, name: "JRPG"},
  {id: 16, name: "Looter Shooter"},
  {id: 17, name: "MMORPG"},
  {id: 18, name: "MOBA"},
  {id: 19, name: "Platformer"},
  {id: 20, name: "Puzzle"},
  {id: 21, name: "Racing"},
  {id: 22, name: "RTS"},
  {id: 23, name: "Rhythm"},
  {id: 24, name: "Roguelike"},
  {id: 25, name: "RPG"},
  {id: 26, name: "Sandbox"},
  {id: 27, name: "Scroll Shooter"},
  {id: 28, name: "Shoot 'Em Up"},
  {id: 29, name: "Simulator"},
  {id: 30, name: "Sports"},
  {id: 31, name: "Stealth Action"},
  {id: 32, name: "Survival"},
  {id: 33, name: "Survival Horror"},
  {id: 34, name: "Top-Down Shooter"},
  {id: 35, name: "Tower Defense"},
  {id: 36, name: "TBS"},
]