name: Test WebAPI
on: [workflow_dispatch, push]
jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Get Repository Code
        uses: actions/checkout@v3
      - name: Run Tests
        working-directory: ./server
        run: dotnet test
